name: Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev zlib1g-dev

    - name: Build
      run: |
        make cpu

    - name: Run Tests
      run: |
        cd tests && make

    - name: Help Command Verification (Dry Run)
      run: ./mandelbrot-desktop --help
